### ISSUE TITLE
it is loading complete db in memory at startup? 

### ISSUE THREAD

**Issue by dabba39** [claygod/coffer#1]
So i need a lot of ram...

**Comment by claygod** [comment]
Upon loading, all your records will be copied to memory.
The maximum size of the stored data is limited by the size of the RAM. It is also worth considering parameter LimitMemory (read about it : https://github.com/claygod/coffer#config)

**Comment by dabba39** [comment]
why would one do that? There should be as little memory usage as possible.

**Comment by claygod** [comment]
This is the database in memory. The disk is used for logging operations and storing data after stopping the database. Therefore, read operations are fast. And if you develop your transactions, no matter how complex they are, they will also be fast enough.
